{% set name = "perl-class-data-inheritable" %}
{% set version = "0.10" %}
{% set sha256 = "aa1ae68a611357b7bfd9a2f64907cc196ddd6d047cae64ef9d0ad099d98ae54a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RS/RSHERER/Class-Data-Inheritable-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Class::Data::Inheritable

about:
  home: https://metacpan.org/pod/Class::Data::Inheritable
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: 'Inheritable, overridable class data'

extra:
  recipe-maintainers:
    - xileF1337
    - conda-forge/perl-packagers
